### ISSUE TITLE
Consider coredns+etcd over powerdns+mariadb

### ISSUE THREAD

**Issue by onedr0p** [rust84/k8s-gitops#5]
I was able to get coredns, etcd and external-dns working. This setup feels much more lightweight than using powerdns.

https://github.com/onedr0p/k3s-gitops/blob/master/deployments/networking/coredns.yaml
https://github.com/onedr0p/k3s-gitops/blob/master/deployments/networking/etcd.yaml
https://github.com/onedr0p/k3s-gitops/blob/master/deployments/networking/external-dns.yaml

**Comment by onedr0p** [comment]
I am only using a custom coredns chart until this gets merged:

https://github.com/helm/charts/pull/23659

**Comment by rust84** [comment]
Successfully moved from PowerDNS to CoreDNS which was quite painless. Thanks for the tip.
