### ISSUE TITLE
Migrate to Fluxv2

### ISSUE THREAD

**Issue by rust84** [rust84/k8s-gitops#7]
Now that Fluxv2 is running in the cluster the next step is to migrate the charts to the Helm Controller.

https://toolkit.fluxcd.io/guides/helm-operator-migration/

- [x] bitwarden
- [x] blocky
- [x] botkube
- [x] cert-manager
- [x] dex
- [x] dex-k8s-authenticator
- [x] external-dns
- [x] hass-postgresql
- [x] home-assistant
- [x] hubot
- [x] hydra
- [x] influxdb
- [x] kube-prometheus-stack
- [x] kured
- [x] loki
- [x] metallb
- [x] minio
- [x] nfs-client-provisioner
- [x] nginx-ingress
- [x] nginx-ingress-ext
- [x] node-red
- [x] nzbget
- [x] oauth2-proxy
- [x] ombi
- [x] organizr
- [x] plex
- [x] powerdns
- [x] powerdns-admin
- [x] powerdns-mariadb
- [x] rabbitmq-ha
- [x] radarr
- [x] rook-ceph
- [x] sonarr
- [x] speedtest
- [x] tautulli
- [x] thanos
- [x] unifi
- [x] uptimerobot-prometheus
- [x] vault
- [x] vault-secrets-operator
- [x] velero

**Comment by onedr0p** [comment]
I just went thru this, feel free to take a look at my repo for anything

https://github.com/onedr0p/home-cluster

**Comment by rust84** [comment]
All releases have been migrated and Fluxv1 is removed.
